# Generated by Django 4.0.2 on 2022-02-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('state', models.CharField(choices=[('A', 'A'), ('C', 'C')], default='A', max_length=5, null=True, verbose_name='State')),
                ('user', models.CharField(max_length=50, unique=True, verbose_name='User')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('identifier_number', models.CharField(max_length=45, verbose_name='Identifier Number')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('state', models.CharField(choices=[('A', 'A'), ('C', 'C')], default='A', max_length=5, null=True, verbose_name='State')),
                ('user', models.CharField(max_length=50, unique=True, verbose_name='User')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('identifier_number', models.CharField(max_length=45, verbose_name='Identifier Number')),
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialists',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('state', models.CharField(choices=[('A', 'A'), ('C', 'C')], default='A', max_length=5, null=True, verbose_name='State')),
                ('title', models.CharField(max_length=250, verbose_name='First Name')),
                ('message', models.TextField(verbose_name='Message')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('attention_date', models.DateField(verbose_name='Attention Date')),
                ('appointment_type', models.CharField(choices=[('P', 'P'), ('A', 'A')], default='P', max_length=50, verbose_name='Appointment Type')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Client')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialist', verbose_name='Specialist')),
            ],
            options={
                'verbose_name': 'Appointments',
            },
        ),
    ]
